In [75]:
import numpy
n = numpy.arange(27)
n


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [76]:
n.reshape(3, 3, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [77]:
m = numpy.asarray([[123,12,123,12,33],[],[]], dtype=object)
m

array([list([123, 12, 123, 12, 33]), list([]), list([])], dtype=object)

In [78]:
import cv2 

In [79]:
im_g = cv2.imread("smallgray.png", 0)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [80]:
cv2.imwrite("test.png", numpy.asarray([[255, 200, 150, 100, 50, 0], [0, 50, 100, 150, 200, 255]], dtype = "uint8"))

True

In [81]:
im_g[1:2, 2:]

array([[255, 255, 147]], dtype=uint8)

In [82]:
print(im_g)

for row in range(len(im_g)):
  for pixel in range(len(im_g[row])):
    if im_g[row][pixel] < 205:
      im_g[row][pixel] -= 50 

cv2.imwrite("tinted.png", im_g)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


True